export enum PokemonType {
    Normal = 'Normal',
    Fire = 'Fire',
    Water = 'Water',
    Grass = 'Grass',
    Electric = 'Electric',
    Ice = 'Ice',
  Fighting = 'Fighting',
    Poison = 'Poison',
    Ground = 'Ground',
    Flying = 'Flying',
    Psychic = 'Psychic',
    Bug = 'Bug',
    Rock = 'Rock',
    Ghost = 'Ghost',
    Dragon = 'Dragon',
    Steel = 'Steel',
    Dark = 'Dark',
    Fairy = 'Fairy',
}

export const TYPE_COLORS: Record<PokemonType, string> = {
    [PokemonType.Normal]: '#A8A77A',
    [PokemonType.Fire]: '#EE8130',
    [PokemonType.Water]: '#6390F0',
    [PokemonType.Grass]: '#7AC74C',
    [PokemonType.Electric]: '#F7D02C',
    [PokemonType.Ice]: '#96D9D6',
    [PokemonType.Fighting]: '#C22E28',
    [PokemonType.Poison]: '#A33EA1',
    [PokemonType.Ground]: '#E2BF65',
    [PokemonType.Flying]: '#A98FF3',
    [PokemonType.Psychic]: '#F95587',
    [PokemonType.Bug]: '#A6B91A',
    [PokemonType.Rock]: '#B6A136',
    [PokemonType.Ghost]: '#735797',
    [PokemonType.Dragon]: '#6F35FC',
    [PokemonType.Steel]: '#B7B7CE',
    [PokemonType.Dark]: '#705746',
    [PokemonType.Fairy]: '#D685AD',
}

export const TYPE_NAMES_ZH: Record<PokemonType, string> = {
    [PokemonType.Normal]: '一般',
    [PokemonType.Fire]: '火',
    [PokemonType.Water]: '水',
    [PokemonType.Grass]: '草',
    [PokemonType.Electric]: '电',
    [PokemonType.Ice]: '冰',
    [PokemonType.Fighting]: '格斗',
    [PokemonType.Poison]: '毒',
    [PokemonType.Ground]: '地面',
    [PokemonType.Flying]: '飞行',
    [PokemonType.Psychic]: '超能力',
    [PokemonType.Bug]: '虫',
    [PokemonType.Rock]: '岩石',
    [PokemonType.Ghost]: '幽灵',
    [PokemonType.Dragon]: '龙',
    [PokemonType.Steel]: '钢',
    [PokemonType.Dark]: '恶',
    [PokemonType.Fairy]: '妖精',
}
